apiVersion: v1
kind: Service
metadata:
  name: node-server-service
spec:
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 30006  # 集群外部访问的端口
      targetPort: 3000
      nodePort: 30006 #注意空格 必须有
  type: NodePort # 根据需要选择 Service 的类型